# Generated by Django 4.0 on 2022-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinguser',
            name='rate_level',
            field=models.IntegerField(choices=[(1, 1)]),
        ),
    ]
