# Generated by Django 4.0 on 2022-02-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ratinguser_rate_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='criticality',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], db_column='Criticality', default='Low', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ratinguser',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person', unique=True),
        ),
    ]
