# Generated by Django 2.2.12 on 2021-12-06 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.TextField()),
                ('deptrole', models.TextField()),
                ('deptcriticality', models.TextField()),
                ('numberofmembers', models.IntegerField()),
                ('criticality', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], db_column='Criticality', default='draft', max_length=20, null=True)),
            ],
            options={
                'unique_together': {('deptname', 'deptrole')},
            },
        ),
        migrations.CreateModel(
            name='GncTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_project_code', models.URLField(db_column='Audit_Project_Code', max_length=100, null=True)),
                ('audit_project_name', models.CharField(db_column='Audit_Project_Name', max_length=100, null=True)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], db_column='Quarter', max_length=100, null=True)),
                ('audit_project_type', models.CharField(blank=True, db_column='Audit_Project_Type', max_length=100, null=True)),
                ('issue_title', models.CharField(db_column='Issue_Title', max_length=50, null=True)),
                ('criticality', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], db_column='Criticality', default='draft', max_length=20, null=True)),
                ('root_cause_analysis', models.CharField(choices=[('PARTIALLY_IMPLEMENTED', 'PARTIALLY_IMPLEMENTED'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_column='Root_Cause_Analysis', max_length=100, null=True)),
                ('recommendation', models.CharField(db_column='Recommendation', max_length=100, null=True)),
                ('action_plan', models.CharField(db_column='Action_Plan', max_length=100, null=True)),
                ('recommendation_state', models.CharField(db_column='Recommendation_State', max_length=100, null=True)),
                ('agreed_implementation_date', models.DateField(blank=True, db_column='Agreed_Implementation_Date', max_length=100, null=True)),
                ('revised_implementation_date', models.DateField(blank=True, db_column='Revised_Implementation_Date', max_length=100, null=True)),
                ('last_status_update', models.DateField(db_column='Last_Status_Update', max_length=100, null=True)),
                ('ageing_days', models.FloatField(db_column='Ageing__Days', max_length=10, null=True)),
                ('actual_implementation_date', models.DateField(blank=True, db_column='Actual_Implementation_Date', max_length=100, null=True)),
                ('owner', models.CharField(db_column='Owner', max_length=100, null=True)),
                ('final_approver', models.CharField(db_column='Final_Approver', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy_strategic_pillar', models.CharField(blank=True, db_column='XY_Strategic_Pillar', max_length=100, null=True)),
                ('xy_strategic_objectives', models.CharField(blank=True, db_column='XY_Strategic_Objectives', max_length=100, null=True)),
                ('risk_category', models.CharField(blank=True, db_column='Risk_Category', max_length=100, null=True)),
                ('risk_description', models.CharField(blank=True, db_column='Risk_Description', max_length=100, null=True)),
                ('likelihood', models.CharField(blank=True, db_column='Likelihood', max_length=100, null=True)),
                ('impact', models.CharField(blank=True, db_column='Impact', max_length=100, null=True)),
                ('risk_rating', models.CharField(blank=True, db_column='Risk_Rating', max_length=100, null=True)),
                ('control_exists_yesno', models.CharField(blank=True, db_column='Control_Exists_YesNo', max_length=100, null=True)),
                ('control_description', models.CharField(blank=True, db_column='Control_Description', max_length=100, null=True)),
                ('control_is_adequate_yesno', models.CharField(blank=True, db_column='Control_is_Adequate_YesNo', max_length=100, null=True)),
                ('recommended_control', models.CharField(blank=True, db_column='Recommended_Control', max_length=100, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=100, null=True)),
                ('kri', models.CharField(blank=True, db_column='KRI', max_length=100, null=True)),
                ('target', models.CharField(blank=True, db_column='Target', max_length=100, null=True)),
                ('dept', models.CharField(blank=True, db_column='Dept', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('personemail', models.EmailField(max_length=254)),
                ('personsdept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governanceandcontrol.Dept')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='GradingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('deptnem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governanceandcontrol.Dept')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='governanceandcontrol.Person')),
            ],
        ),
    ]
