# Generated by Django 4.0 on 2022-02-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governance_And_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_project_code', models.CharField(db_column='Audit_Project_Code', max_length=100, null=True)),
                ('audit_project_name', models.CharField(db_column='Audit_Project_Name', max_length=100, null=True)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], db_column='Quarter', max_length=100, null=True)),
                ('audit_project_type', models.CharField(blank=True, choices=[('Business', 'Business'), ('ICT', 'ICT'), ('Corporate Affairs', 'Corporate Affairs')], db_column='Audit_Project_Type', max_length=100, null=True)),
                ('issue_title', models.CharField(db_column='Issue_Title', max_length=50, null=True)),
                ('criticality', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], db_column='Criticality', default='draft', max_length=20, null=True)),
                ('root_cause_analysis', models.CharField(choices=[('POCESSES', 'POCESSES'), ('PEOPLE', 'PEOPLE'), ('TECHNOLOGY', 'TECHNOLOGY')], db_column='Root_Cause_Analysis', max_length=100, null=True)),
                ('recommendation', models.CharField(db_column='Recommendation', max_length=100, null=True)),
                ('action_plan', models.CharField(db_column='Action_Plan', max_length=100, null=True)),
                ('recommendation_state', models.CharField(choices=[('PARTIALLY_IMPLEMENTED', 'PARTIALLY_IMPLEMENTED'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_column='Recommendation_State', max_length=100, null=True)),
                ('agreed_implementation_date', models.DateField(blank=True, db_column='Agreed_Implementation_Date', max_length=100, null=True)),
                ('revised_implementation_date', models.DateField(blank=True, db_column='Revised_Implementation_Date', max_length=100, null=True)),
                ('last_status_update', models.DateField(db_column='Last_Status_Update', max_length=100, null=True)),
                ('ageing_days', models.FloatField(db_column='Ageing__Days', max_length=10, null=True)),
                ('actual_implementation_date', models.DateField(blank=True, db_column='Actual_Implementation_Date', max_length=100, null=True)),
                ('final_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
        ),
    ]
