# Generated by Django 2.2.12 on 2021-12-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='deptcriticality',
        ),
    ]
