# Generated by Django 2.2.12 on 2021-12-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='audit_project_code',
            field=models.CharField(db_column='Audit_Project_Code', max_length=100, null=True),
        ),
    ]
