# Generated by Django 2.2.12 on 2021-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy_strategic_pillar', models.CharField(blank=True, db_column='XY_Strategic_Pillar', max_length=100, null=True)),
                ('xy_strategic_objectives', models.CharField(blank=True, db_column='XY_Strategic_Objectives', max_length=100, null=True)),
                ('risk_category', models.CharField(blank=True, db_column='Risk_Category', max_length=100, null=True)),
                ('risk_description', models.CharField(blank=True, db_column='Risk_Description', max_length=100, null=True)),
                ('likelihood', models.CharField(blank=True, db_column='Likelihood', max_length=100, null=True)),
                ('impact', models.CharField(blank=True, db_column='Impact', max_length=100, null=True)),
                ('risk_rating', models.CharField(blank=True, db_column='Risk_Rating', max_length=100, null=True)),
                ('control_exists_yesno', models.CharField(blank=True, db_column='Control_Exists_YesNo', max_length=100, null=True)),
                ('control_description', models.CharField(blank=True, db_column='Control_Description', max_length=100, null=True)),
                ('control_is_adequate_yesno', models.CharField(blank=True, db_column='Control_is_Adequate_YesNo', max_length=100, null=True)),
                ('recommended_control', models.CharField(blank=True, db_column='Recommended_Control', max_length=100, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=100, null=True)),
                ('kri', models.CharField(blank=True, db_column='KRI', max_length=100, null=True)),
                ('target', models.CharField(blank=True, db_column='Target', max_length=100, null=True)),
                ('dept', models.CharField(blank=True, db_column='Dept', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GncTable',
        ),
    ]
