# Generated by Django 2.2.12 on 2021-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], db_column='Quarter', max_length=100, null=True),
        ),
    ]
