# Generated by Django 2.2.12 on 2021-12-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0002_auto_20211202_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='criticality',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], db_column='Criticality', default='draft', max_length=20, null=True),
        ),
    ]
