# Generated by Django 2.2.12 on 2021-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0002_remove_dept_deptcriticality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dept',
            name='deptrole',
            field=models.CharField(max_length=100),
        ),
    ]
