# Generated by Django 2.2.12 on 2021-12-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0002_auto_20211208_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='recommendation',
            field=models.CharField(choices=[('PARTIALLY_IMPLEMENTED', 'PARTIALLY_IMPLEMENTED'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_column='Recommendation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='root_cause_analysis',
            field=models.CharField(choices=[('POCESSES', 'POCESSES'), ('PEOPLE', 'PEOPLE'), ('TECHNOLOGY', 'TECHNOLOGY')], db_column='Root_Cause_Analysis', max_length=100, null=True),
        ),
    ]
