# Generated by Django 2.2.12 on 2021-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0002_auto_20211202_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='GncTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_project_code', models.CharField(blank=True, db_column='Audit_Project_Code', max_length=100, null=True)),
                ('audit_project_name', models.CharField(blank=True, db_column='Audit_Project_Name', max_length=100, null=True)),
                ('quarter', models.CharField(blank=True, db_column='Quarter', max_length=100, null=True)),
                ('audit_project_type', models.CharField(blank=True, db_column='Audit_Project_Type', max_length=100, null=True)),
                ('issue_title', models.CharField(blank=True, db_column='Issue_Title', max_length=100, null=True)),
                ('criticality', models.CharField(blank=True, db_column='Criticality', max_length=100, null=True)),
                ('root_cause_analysis', models.CharField(blank=True, db_column='Root_Cause_Analysis', max_length=100, null=True)),
                ('recommendation', models.CharField(blank=True, db_column='Recommendation', max_length=100, null=True)),
                ('action_plan', models.CharField(blank=True, db_column='Action_Plan', max_length=100, null=True)),
                ('recommendation_state', models.CharField(blank=True, db_column='Recommendation_State', max_length=100, null=True)),
                ('agreed_implementation_date', models.CharField(blank=True, db_column='Agreed_Implementation_Date', max_length=100, null=True)),
                ('revised_implementation_date', models.CharField(blank=True, db_column='Revised_Implementation_Date', max_length=100, null=True)),
                ('last_status_update', models.CharField(blank=True, db_column='Last_Status_Update', max_length=100, null=True)),
                ('ageing_days', models.FloatField(blank=True, db_column='Ageing__Days', null=True)),
                ('actual_implementation_date', models.CharField(blank=True, db_column='Actual_Implementation_Date', max_length=100, null=True)),
                ('owner', models.CharField(blank=True, db_column='Owner', max_length=100, null=True)),
                ('final_approver', models.CharField(blank=True, db_column='Final_Approver', max_length=100, null=True)),
            ],
        ),
    ]
