# Generated by Django 2.2.12 on 2021-12-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0003_auto_20211202_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='root_cause_analysis',
            field=models.CharField(choices=[('PARTIALLY_IMPLEMENTED', 'PARTIALLY_IMPLEMENTED'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_column='Root_Cause_Analysis', max_length=100, null=True),
        ),
    ]
