# Generated by Django 2.2.12 on 2021-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0003_gnctable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='agreed_implementation_date',
            field=models.DateField(blank=True, db_column='Agreed_Implementation_Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='last_status_update',
            field=models.DateField(blank=True, db_column='Last_Status_Update', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='revised_implementation_date',
            field=models.DateField(blank=True, db_column='Revised_Implementation_Date', max_length=100, null=True),
        ),
    ]
