# Generated by Django 2.2.12 on 2021-12-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0004_auto_20211202_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='actual_implementation_date',
            field=models.DateField(blank=True, db_column='Actual_Implementation_Date', max_length=100, null=True),
        ),
    ]
