# Generated by Django 2.2.12 on 2021-12-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0004_auto_20211202_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnctable',
            name='action_plan',
            field=models.CharField(db_column='Action_Plan', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='ageing_days',
            field=models.FloatField(db_column='Ageing__Days', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='audit_project_code',
            field=models.URLField(db_column='Audit_Project_Code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='audit_project_name',
            field=models.CharField(db_column='Audit_Project_Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='final_approver',
            field=models.CharField(db_column='Final_Approver', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='issue_title',
            field=models.CharField(db_column='Issue_Title', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='last_status_update',
            field=models.DateField(db_column='Last_Status_Update', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='owner',
            field=models.CharField(db_column='Owner', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='recommendation',
            field=models.CharField(db_column='Recommendation', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='recommendation_state',
            field=models.CharField(db_column='Recommendation_State', max_length=100, null=True),
        ),
    ]
