# Generated by Django 2.2.12 on 2021-12-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governanceandcontrol', '0006_auto_20211209_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorofauditors',
            name='actual_implementation_date',
            field=models.DateField(blank=True, db_column='Actual_Implementation_Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditorofauditors',
            name='agreed_implementation_date',
            field=models.DateField(blank=True, db_column='Agreed_Implementation_Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditorofauditors',
            name='current_status_at_xy',
            field=models.CharField(blank=True, choices=[('PARTIALLY_IMPLEMENTED', 'PARTIALLY_IMPLEMENTED'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_column='Current_Status_at_XY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditorofauditors',
            name='recommendation_state',
            field=models.CharField(blank=True, choices=[('PARTIALLY_IMPLEMENTED', 'PARTIALLY_IMPLEMENTED'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], db_column='Recommendation_State', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditorofauditors',
            name='revised_implementation_date',
            field=models.DateField(blank=True, db_column='Revised_Implementation_Date', max_length=100, null=True),
        ),
    ]
