# Generated by Django 4.0 on 2021-12-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor_of_auditors', '0002_alter_auditorofauditors_final_approver'),
        ('accounts', '0003_dept_person_gradinguser'),
        ('governanceandcontrol', '0011_alter_dept_id_alter_gnctable_id_alter_gradinguser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradinguser',
            name='deptnem',
        ),
        migrations.RemoveField(
            model_name='gradinguser',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='personsdept',
        ),
        migrations.RemoveField(
            model_name='riskmanagement',
            name='dept',
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='final_approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
        ),
        migrations.AlterField(
            model_name='gnctable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dept'),
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='GradingUser',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='RiskManagement',
        ),
    ]
