# Generated by Django 4.0 on 2021-12-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_dept_person_gradinguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xy_strategic_pillar', models.CharField(blank=True, db_column='XY_Strategic_Pillar', max_length=100, null=True)),
                ('xy_strategic_objectives', models.CharField(blank=True, db_column='XY_Strategic_Objectives', max_length=100, null=True)),
                ('risk_category', models.CharField(blank=True, choices=[('Financial_Liquidity', 'Financial_Liquidity'), ('Financial_Interest_Rate', 'Financial_Interest_Rate'), ('Financial_Foreign_Exchange', 'Financial_Foreign_Exchange'), ('Financial_Investment', 'Financial_Investment'), ('Financial_Market', 'Financial_Market'), ('Operational_Transaction', 'Operational_Transaction'), ('Operational_Human_Resources', 'Operational_Human_Resources'), ('Operational_ICT', 'Operational_ICT'), ('Operational_Fraud', 'Operational_Fraud'), ('Legal', 'Legal'), ('Compliance', 'Compliance'), ('Strategic', 'Strategic'), ('Reputation', 'Reputation'), ('Governance', 'Governance'), ('Other', 'Other')], db_column='Risk_Category', max_length=100, null=True)),
                ('risk_description', models.CharField(blank=True, db_column='Risk_Description', max_length=100, null=True)),
                ('likelihood', models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Likelihood', max_length=100, null=True)),
                ('impact', models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Impact', max_length=100, null=True)),
                ('risk_rating', models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Risk_Rating', max_length=100, null=True)),
                ('control_exists_yesno', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], db_column='Control_Exists_YesNo', max_length=100, null=True)),
                ('control_description', models.CharField(blank=True, db_column='Control_Description', max_length=100, null=True)),
                ('control_is_adequate_yesno', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], db_column='Control_is_Adequate_YesNo', max_length=100, null=True)),
                ('recommended_control', models.CharField(blank=True, db_column='Recommended_Control', max_length=100, null=True)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=100, null=True)),
                ('kri', models.CharField(blank=True, db_column='KRI', max_length=100, null=True)),
                ('target', models.CharField(blank=True, db_column='Target', max_length=100, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dept')),
            ],
        ),
    ]
