# Generated by Django 4.0 on 2022-02-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='likelihood',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Likelihood', max_length=100),
        ),
    ]
