# Generated by Django 4.0 on 2022-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0003_alter_riskmanagement_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='likelihood',
            field=models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Likelihood', default='low', max_length=100),
        ),
    ]
