# Generated by Django 4.0 on 2022-02-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0004_alter_riskmanagement_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='control_exists_yesno',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], db_column='Control_Exists_YesNo', default='no', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='control_is_adequate_yesno',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], db_column='Control_is_Adequate_YesNo', default='no', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='impact',
            field=models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Impact', default='low', max_length=100),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Risk_Rating', max_length=100, null=True),
        ),
    ]
