# Generated by Django 4.0 on 2022-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0005_alter_riskmanagement_control_exists_yesno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='risk_rating',
            field=models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], db_column='Risk_Rating', default='low', max_length=100, null=True),
        ),
    ]
