# Generated by Django 4.0 on 2022-02-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmanagement', '0006_alter_riskmanagement_risk_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='risk_description',
            field=models.TextField(blank=True, db_column='Risk_Description', max_length=100, null=True),
        ),
    ]
