# Generated by Django 4.0 on 2022-02-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_deptnem_ratinguser_department'),
        ('auditor_of_auditors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auditorofauditors',
            new_name='Auditor_of_auditors',
        ),
    ]
