# Generated by Django 4.0 on 2021-12-13 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dept_person_gradinguser'),
        ('auditor_of_auditors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorofauditors',
            name='final_approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
        ),
    ]
